name = "Leaflet"
uuid = "2ed2781b-9bfa-45ba-823d-d31db75b7d93"
authors = ["Yeesian Ng <ngyeesian@gmail.com>, Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
GeoJSON = "61d90e0f-e114-555e-ac52-39dfb47a3ef9"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"
TileProviders = "263fe934-28e1-4ae9-998a-c2629c5fede6"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[compat]
Colors = "0.12"
GeoInterface = "1"
GeoJSON = "0.6"
JSON3 = "1"
TileProviders = "0.1.0"
WebIO = "0.8"
julia = "1"

[extras]
GADM = "a8dd9ffe-31dc-4cf5-a379-ea69100a8233"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["GADM", "Test"]
